### ISSUE TITLE
Latest update broke controls

### ISSUE THREAD

**Issue by TheGameratorT** [ipodtouch0218/NSMB-MarioVsLuigi#102] opened 2022-09-01 15:23 UTC
In the latest version the UI controls conflict with the Game controls for the "Sprint, Jump, and other action keys" which makes some keys that are conflicting just do nothing.
My current work around is to just set all UI keybinds a letter that I don't use.

**Comment by ipodtouch0218** [comment] 2022-12-08 16:59
Duplicate of #76

**Closed by ipodtouch0218** 2022-12-08 16:59 UTC
