### ISSUE TITLE
Small but rare collision bug with koopa shell when falling off the map after being destroyed

### ISSUE THREAD

**Issue by Proxofer** [ipodtouch0218/NSMB-MarioVsLuigi#112] opened 2022-09-08 08:29 UTC
i dont have much information and it only happened to me once by now, but i recently experienced a bug which made a koopa troopa shell that got destroyed float where-ever i walked to, as if sticked onto my character.

**Comment by SLG64** [comment] 2022-09-08 14:36
It's the thing that gave me the idea for pets. But still, There's been The Tumbleweed Spiny, Moonwalking Goomba, and The Ghostly Koopa.

**Comment by ipodtouch0218** [comment] 2022-12-08 17:39
Duplicate of #96

**Closed by ipodtouch0218** 2022-12-08 17:39 UTC
