### ISSUE TITLE
Controller not working properly in the download version

### ISSUE THREAD

**Issue by TheCheekiBreekiest** [ipodtouch0218/NSMB-MarioVsLuigi#84] opened 2022-08-02 19:09 UTC
Using a controller (Switch Pro in my case) on the downloaded version of MvL is very buggy. It keeps pulling left and jumping for no reason without any outside input.
https://youtu.be/W-uKFjAooqY
Everything works fine in the browser version.

**Comment by ipodtouch0218** [comment] 2022-12-08 16:54
Duplicate of #76

**Closed by ipodtouch0218** 2022-12-08 16:54 UTC
