### ISSUE TITLE
There Should Be 4 Teams In Team Mode!

### ISSUE THREAD

**Issue by TheMarioSuperStar** [ipodtouch0218/NSMB-MarioVsLuigi#187] opened 2023-05-06 02:52 UTC
Because team mode is confirmed for the game, you shouldn't just do "Team Mario VS Team Luigi" You should add 3 different teams modes: "Team Mario VS Team Luigi" "Team Blue VS Team Red VS Team Green" and "Team Blue VS Team Red VS Team Green VS Team Yellow" Here is a image I made that could show what it looks like:
![TeamBlueTest01WithPlayers](https://user-images.githubusercontent.com/109318753/236594750-ab99f801-a13b-44e1-8e97-fd454e7ab8d7.png)
Also, if you don't have time to add the 4 teams in the next update, you should add Team Mario VS Team Luigi in the next one, and then the 4 teams in a later update.

Edit: With 3 teams and 4 teams, your shirt color should change depending your team color. And players will have black overalls.

**Comment by ipodtouch0218** [comment] 2023-07-16 05:02
Closed as duplicate of #68

**Closed by ipodtouch0218** 2023-07-16 05:02 UTC
