### ISSUE TITLE
binding the jump key to W rarely works

### ISSUE THREAD

**Issue by mse-k** [ipodtouch0218/NSMB-MarioVsLuigi#185] opened 2023-04-27 22:44 UTC
when bound as w and unbinding the regular w keybind, the game refuses to jump unless you hold up arrow while tapping w, its generally inconsistent though and sometimes will work once without holding up, and works fine when bound to any other key

**Comment by ipodtouch0218** [comment] 2023-07-16 05:06
Duplicate of #156

**Closed by ipodtouch0218** 2023-07-16 05:06 UTC
