### ISSUE TITLE
Weird D-pad support

### ISSUE THREAD

**Issue by DBPT210** [ipodtouch0218/NSMB-MarioVsLuigi#89] opened 2022-08-12 15:39 UTC
I like playing this game with a controller. The only I have is a PS4 controller (Dualshock 4). While using the D-pad, sometimes the player can just stop while hold left or right and doing other actions, such as jump and using the powerup. It can also happened when going left and right nonstop. Because of this, I am forced to use the joystick.

**Comment by ipodtouch0218** [comment] 2022-12-08 16:55
Duplicate of #76

**Closed** 2022-12-08 17:40 UTC
Labels: duplicate
