### ISSUE TITLE
Movement randomly stops

### ISSUE THREAD

**Issue by EinsKatze** [ipodtouch0218/NSMB-MarioVsLuigi#73] opened 2022-07-17 20:14 UTC
My Movement im pressing stops working randomly.
Watch the Video below to see what i mean.

https://user-images.githubusercontent.com/82060534/179423267-06e25cdf-7bbe-45a7-aaf8-6d0f6cd81e1d.mp4

**Comment by ShadowWalker13** [comment] 2022-07-17 22:36
Are you using the dpad on a controller?
If so, you can try to fix this by setting both the primary and secondary movement controls to the dpad.

**Comment by EinsKatze** [comment] 2022-07-18 05:49
> Are you using the dpad on a controller?

No im using my normal Keyboard (_Roccat Vulcan TKL Pro_)

On my Laptop it does work, so it seems to be a Problem with my Keyboard.

**Comment by EinsKatze** [comment] 2022-07-18 17:35
Yea seems like i had a controller connected that made minimal input.
I did not touch the controller tho.

**Comment by ipodtouch0218** [comment] 2022-12-22 19:47
Duplicate of #76 (technically, this was made before, but more clear discussion is happening there)

**Comment by ipodtouch0218** [comment] 2022-12-22 19:47
Duplicate of #76

**Closed by ipodtouch0218** 2022-12-22 19:47 UTC
Labels: bug, needs-info
