### ISSUE TITLE
Make a level Creator

### ISSUE THREAD

**Issue by FiveSpade** [ipodtouch0218/NSMB-MarioVsLuigi#121] opened 2022-09-18 06:11 UTC
This would increase the speed of map making tenfold and also allow community member to easily make their own maps, allow custom image porting for backgrounds as well as custom importing tiles to make new themes

**Comment by SLG64** [comment] 2022-09-20 15:05
Technically Mario Maker battle mode?

**Comment by SLG64** [comment] 2022-09-21 16:57
If this feature was added, there would have to be certain pieces for the different styles, seeing as how **Super Mario Maker 2** has a crap ton of "Little Timmy" levels that drives everyone mad. There would also have to be a limited amount of objects and power-ups. It would be sad if we started to get those crappy levels, but an editor would be nice.

**Comment by FiveSpade** [comment] 2022-09-21 18:45
I see your point, I think best way to add it would be after you upload a map you have the have a huge list of community made maps then official custom maps then you could search for specific maps using a code. I’m not really sure how to negate the little Timmy problem other then getting like 100 official map makers that know what they’re doing and they can make maps that go in community maps and they only way to look at/play on a normal players maps would be with a code

**Comment by SLG64** [comment] 2022-09-21 19:17
So the thing would be like the layout of all the playable levels in the Super Mario Construct community? You'd have to copy the code or link and then you'd be able to play, correct?

**Comment by FiveSpade** [comment] 2022-09-21 21:36
Yeah

**Comment by SLG64** [comment] 2022-09-22 13:20
I think this is halarious, but I littirally had a dream this morning of what it might look like. I only thought of "Mario Spawn Point" and "Luigi Spawn Point" which seems weird, seeing as all players spawn together in one spot.

**Comment by ipodtouch0218** [comment] 2022-09-24 18:26
I think the unity editor is good/simple enough to create a level. Being able to share levels however is a different story entirely.

**Comment by FiveSpade** [comment] 2022-09-25 18:15
> I think the unity editor is good/simple enough to create a level. Being able to share levels however is a different story entirely.

What if you used an external website and that would be the Official place to put level codes for people to play on?

**Comment by SLG64** [comment] 2022-09-26 14:13
Maybe something like LevelPalace?

**Comment by PoketrainerMS** [comment] 2022-10-17 15:32
Honestly is you just want to play it with friends, edit a map in Unity, and share the build with the changes to the people who are going to play it too, and choose the map you edited.

**Comment by NathenHero38** [comment] 2022-12-02 18:39
maybe the editer would be used ingame

**Comment by ipodtouch0218** [comment] 2022-12-08 16:52
Closing as a duplicate of #94. Please use that issue instead.

**Comment by ipodtouch0218** [comment] 2022-12-08 16:53
Duplicate of #94

**Closed by ipodtouch0218** 2022-12-08 16:52 UTC
Labels: duplicate, new-feature
