### ISSUE TITLE
CustomAuth Service or Bad Gateway - 502 Error

### ISSUE THREAD

**Issue by TheGamingTime** [ipodtouch0218/NSMB-MarioVsLuigi#152] opened 2022-12-19 14:45 UTC
this has been going on for 30 minutes or so im nto really sure. Its been bugging me for quite a while. Incase youre wondering. I'm connected to the eu servers, and have no way to change it since it struggles to connect into a shut down server for 5 minutes. then it tells me one of either of these errors

- HTTP/1.1 502 Bad Gateway - 502
- CustomAuth service error: RequestTimeout
- there was another one but it doesnt wanna show up by me again hhhhh

anyways yea i hope this could get fixed soon and yea

**Comment by TheGamingTime** [comment] 2022-12-20 09:30
A friend of mine got the same issue with this even when the servers by me where working fine, so i decided to reopen it for now

**Comment by ipodtouch0218** [comment] 2022-12-22 19:42
Duplicate of #149

**Closed by ipodtouch0218** 2022-12-22 19:42 UTC
